### ISSUE TITLE
Add 'Opportunity Type' field to Mankins Pipeline Snapshot

### ISSUE THREAD

**Issue by mmankins** [boomii/bdw#173]
Hey,

Would be great to get the 'Opportunity_Type' field added to the pipeline snapshot file I get weekly. Looking to differentiate between incremental, new business, and partner.

-MM

**Comment by coreywebber** [comment]
**Drop** 
Goto_Market_Parent
Goto_Market_Referral
Quarterly_Commit
Opportunity_Category_Parent
Opportunity_Category

**Add**
Opportunity   Type (Incremental, New Business, Monthly, Partner Acquisition)
Rep   Created by Division

**Comment by coreywebber** [comment]
fingers crossed
