### ISSUE TITLE
Add Rep 'Created by Division' to Mankins Pipeline Snapshot

### ISSUE THREAD

**Issue by mmankins** [boomii/bdw#189]
Another one for you -- we're looking at segmenting pipeline by who created it (categories will be BDR, Field Sales, Channel Sales). I think I can accomplish this by including the 'Created by Division' field you have in the Cube to the Mankins Pipe Snapshots. 

-MM

![image](https://user-images.githubusercontent.com/58782358/72480470-61a00100-37ac-11ea-9283-56ac12f90405.png)

**Comment by coreywebber** [comment]
so for about every field we add it adds on about a. Ton of time for processing to compile. Just an FYI, this is why we had to narrow the number of columns down for Pace originally.

As an example it took 2 hours to run what I was running for Pace, added a column columns for you, and now it's 4, added the 2 others and it's still not finished running it's from earlier.

so we will have to scale back what you're looking for, if you wanted to run within 24 hour lol. it doesn't help that refreshes are happening in the middle of the query either :)

Sent from Workspace ONE Boxer

On Jan 15, 2020 5:33 PM, mmankins <notifications@github.com> wrote:

[EXTERNAL EMAIL]

Another one for you -- we're looking at segmenting pipeline by who created it (categories will be BDR, Field Sales, Channel Sales). I think I can accomplish this by including the 'Created by Division' field you have in the Cube to the Mankins Pipe Snapshots.

-MM

[image]<https://user-images.githubusercontent.com/58782358/72480470-61a00100-37ac-11ea-9283-56ac12f90405.png>

-
