### ISSUE TITLE
New Cube Field: Closed Date Fiscal Day of Qtr

### ISSUE THREAD

**Issue by mmankins** [boomii/bdw#284]
Hey There,

There's now some heavy focus on measuring closed $ACV on a daily basis v. historicals. If it is an easy add, can a new Cube date grouping be created called "Closed Date Fiscal Day of Quarter"? Same concept as "Close Date Fiscal Week of Quarter", just down to the Day (1-91) rather than week.

LMK if any questions. Thanks!
-Matthew

**Comment by coreywebber** [comment]
Added Closed_Day_of_Quarter to the view
